MNC-TEAM/Tripot_backend

build.gradle
module-api/src/main/resources/application-api-prod.yml
module-common/src/main/resources/application-common-prod.yml
module-domain/src/main/resources/application-domain-local.yml
module-domain/src/main/resources/application-domain-prod.yml

prod yml 파일에 환경변수를 aws parameterstore에서 가져오도록 변경

11차 CI/CD 테스트

---

module-api/src/main/resources/application-api-prod.yml
module-common/src/main/resources/application-common-prod.yml
module-domain/src/main/resources/application-domain-prod.yml

profile-separator: _ -> - (default value)

13차 CI/CD 테스트

---

build.gradle

- aws parameterstore version: 3.1.0 -> 3.2.0

15차 CI/CD 테스트

---

module-api/src/main/resources/application-api-prod.yml
module-common/src/main/resources/application-common-prod.yml
module-domain/src/main/resources/application-domain-prod.yml

- aws.paramstore 제거
- import key 값 추가

18차 CI/CD 테스트

---

module-api/src/main/java/com/junior/controller/MemberController.java
module-api/src/main/java/com/junior/controller/ReissueController.java
module-api/src/main/java/com/junior/security/filter/JWTFilter.java
module-api/src/main/java/com/junior/service/MemberService.java
module-api/src/main/java/com/junior/service/ReissueService.java
module-api/src/main/java/com/junior/service/s3/S3Service.java
module-api/src/main/resources/application-api-local.yml
module-api/src/main/resources/application-api-prod.yml
module-common/src/main/java/com/junior/exception/StatusCode.java
module-domain/src/main/java/com/junior/domain/member/Member.java
module-domain/src/main/java/com/junior/dto/member/MemberInfoDto.java

다음의 기능 추가
- 프로필 사진 변경
- 회원 조회
- reissue

Feature/회원 관련 기능

---

module-api/src/main/java/com/junior/config/SecurityConfig.java
module-api/src/main/java/com/junior/security/JwtUtil.java
module-api/src/main/java/com/junior/security/filter/JWTFilter.java
module-api/src/main/java/com/junior/security/filter/JwtValidExceptionHandlerFilter.java
module-api/src/main/java/com/junior/service/OAuth2Service.java
module-api/src/main/java/com/junior/service/ReissueService.java
module-common/src/main/java/com/junior/exception/StatusCode.java
module-domain/src/main/java/com/junior/util/RedisUtil.java

- 액세스 토큰의 만료 기한을 한시간으로 수정
- 토큰 유효성 검증 필터 추가

reissue 관련

---

module-api/build.gradle
module-api/src/main/java/com/junior/config/SwaggerConfig.java
module-api/src/main/java/com/junior/controller/MemberController.java
module-api/src/main/java/com/junior/response/CommonResponse.java
module-api/src/main/java/com/junior/security/filter/JwtValidExceptionHandlerFilter.java
module-api/src/main/java/com/junior/service/MemberService.java
module-common/src/main/java/com/junior/exception/StatusCode.java

- CommonResponse에 status 추가
- Jwt 검증 로직 오류 수정

jwt 관련 오류 수정

---

module-api/src/main/java/com/junior/config/SecurityConfig.java
module-api/src/main/java/com/junior/handler/ApiExceptionHandler.java
module-api/src/main/java/com/junior/security/exceptionhandler/CustomAuthenticationEntryPoint.java
module-api/src/main/java/com/junior/security/filter/JwtValidExceptionHandlerFilter.java
module-common/src/main/java/com/junior/exception/StatusCode.java

- 스프링 시큐리티 관련 예외 처리
- UnknownError 로그 추가

회원 관련 예외 처리

---

module-api/src/main/java/com/junior/controller/StoryController.java
module-api/src/main/java/com/junior/service/story/StoryService.java
module-common/src/main/java/com/junior/exception/StatusCode.java
module-domain/src/main/java/com/junior/domain/story/Story.java
module-domain/src/main/java/com/junior/dto/story/ResponseStoryCntByCityDto.java
module-domain/src/main/java/com/junior/dto/story/SearchAndCityDto.java
module-domain/src/main/java/com/junior/repository/story/custom/StoryCustomRepository.java
module-domain/src/main/java/com/junior/repository/story/custom/StoryCustomRepositoryImpl.java
module-domain/src/test/java/com/junior/domain/repository/story/StoryCustomRepositoryImplTest.java

1. 검색어 + 지역 별 스토리 조회
2. 도시 별 스토리 수 조회
3. 지도 기반 스토리 조회(페이징)
4. 지도 기반 스토리 조회(전체 스토리)

story api 추가

---

module-domain/src/main/resources/application-domain-prod.yml

ddl auto 업데이트

---

module-domain/src/main/java/com/junior/repository/story/custom/StoryCustomRepositoryImpl.java

eqCursorId 비교하는 로직이 인기순으로 정렬하는 로직이랑 달라서 2중으로 정렬되는 버그 수정

최근 인기있는 스토리 중복 조회 이슈

---

module-api/src/main/java/com/junior/controller/login/OAuth2Controller.java
module-api/src/main/java/com/junior/service/member/OAuth2Service.java
module-api/src/test/java/com/junior/controller/login/OAuth2ControllerTest.java
module-api/src/test/java/com/junior/integration/BaseIntegrationTest.java
module-api/src/test/java/com/junior/integration/login/OAuth2IntegrationTest.java
module-api/src/test/java/com/junior/service/member/OAuth2ServiceTest.java
module-domain/src/main/java/com/junior/dto/oauth2/OAuth2LoginDto.java

- 클라이언트에서 oauth2 처리를 하여 받은 유저 정보를 서버로 받는 형식으로 변경

소셜 로그인 방식 재구성

---

module-api/build.gradle
module-api/src/main/java/com/junior/config/SecurityConfig.java
module-api/src/main/resources/application.yml

무중단 배포 2차 테스트

---

module-domain/src/main/resources/application-domain-prod.yml

무중단 배포 4차 테스트

---

module-api/src/main/java/com/junior/config/SecurityConfig.java

securityConfig 수정

---

module-api/src/main/java/com/junior/security/JwtUtil.java

- 1시간 -> 5분
- 테스트 후 반드시 원상태로 복구시킬 것

access token expire time 조정

---

module-api/src/main/java/com/junior/security/JwtUtil.java

This reverts commit d8c24c63594996b42598a02dcdbf539e88e7f15c.
- access token exp 조정 롤백: 5m->1h

Revert "access token expire time 조정"

---

module-domain/src/main/java/com/junior/domain/member/Member.java
module-domain/src/test/java/com/junior/repository/story/StoryCustomRepositoryImplTest.java

- 다음의 미사용 필드 제거
- isAgreeTermsUse
- isAgreeCollectingUsingPersonalInformation
- isAgreeMarketing
- Auditing 적용

Fix/회원 일부 필드 수정

---

module-api/src/main/java/com/junior/config/ScanConfig.java
module-api/src/main/resources/application-api-dev.yml
module-api/src/main/resources/application-api-local.yml
module-api/src/main/resources/application-api-prod.yml
module-api/src/main/resources/application-api.yml
module-api/src/main/resources/application.yml
module-api/src/test/java/com/junior/integration/BaseIntegrationTest.java
module-api/src/test/java/com/junior/integration/comment/CommentAdminIntegrationTest.java
module-api/src/test/java/com/junior/integration/login/OAuth2IntegrationTest.java
module-api/src/test/java/com/junior/integration/member/MemberIntegrationTest.java
module-api/src/test/java/com/junior/integration/notice/NoticeAdminIntegrationTest.java
module-api/src/test/java/com/junior/integration/notice/NoticeUserIntegrationTest.java
module-api/src/test/java/com/junior/integration/qna/QnaAdminIntegrationTest.java
module-api/src/test/java/com/junior/integration/qna/QnaUserIntegrationTest.java
module-api/src/test/java/com/junior/integration/report/ReportIntegrationTest.java
module-api/src/test/java/com/junior/integration/story/AdminStoryIntegrationTest.java
module-common/src/main/resources/application-common-dev.yml
module-common/src/main/resources/application-common-local.yml
module-common/src/main/resources/application-common-prod.yml
module-domain/build.gradle
module-domain/src/main/resources/application-domain-dev.yml
module-domain/src/main/resources/application-domain-local.yml
module-domain/src/main/resources/application-domain-prod.yml
module-domain/src/main/resources/application-domain.yml

- 일부 테스트코드 작성
- Notice, Q&A 관련
- application.yml 파일 관련 대거 수정
- 공통 저장요소를 묶어서 적용
- 일부 요소를 환경변수로 관리하도록 수정
- 미사용 파일 제거

일부 리팩토링 사항 적용

---

module-api/src/main/java/com/junior/config/firebaseConfig.java
module-api/src/main/java/com/junior/controller/S3Controller.java

3s 파일 업로드 API 추가

---

module-api/src/main/java/com/junior/security/JwtUtil.java

액세스 토큰 exp 임시 변경

---

module-domain/src/main/java/com/junior/event/CommentEventListener.java

댓글 이벤트 리스너 수정

---

module-api/src/main/java/com/junior/config/SecurityConfig.java
module-api/src/main/java/com/junior/controller/api/PopUpEventApi.java
module-api/src/main/java/com/junior/controller/popUpEvent/PopUpEventController.java
module-api/src/main/java/com/junior/service/popUpEvent/PopUpEventService.java
module-domain/src/main/java/com/junior/repository/popUpEvent/PopUpEventCustomRepository.java
module-domain/src/main/java/com/junior/repository/popUpEvent/PopUpEventCustomRepositoryImpl.java

- 운영자가 조회할 수 있는 페이지 반환 추가
- 팝업 스토어 조회는 비 로그인 유저도 가능하도록 수정
- put -> patch 수정

팝업 스토어 기능 추가

---

module-api/src/main/java/com/junior/controller/popUpEvent/PopUpEventController.java

- popUpEvnetId, popUpId 서로 이름이 맞지 않아 파싱하지 못하는 버그 수정

팝업 스토어 단일 조회 API 버그 수정

---

module-api/src/main/java/com/junior/config/SecurityConfig.java

- security 경로 상 오타 수정(vi -> v1)

팝업 이벤트 조회 버그 수정

---

module-api/src/main/java/com/junior/controller/popUpEvent/PopUpEventLikeController.java
module-api/src/main/java/com/junior/service/popUpEvent/PopUpEventService.java

- 비회원 유저가 팝업 스토어를 조회할 수 없었던 버그 수정
- 팝업 스토어 좋아요 삭제 API 동작 안하던 버그 수정

팝업 스토어 버그 수정

---

module-api/src/main/java/com/junior/service/popUpEvent/PopUpEventLikeService.java

팝업 스토어 좋아요 삭제 버그 수정
